/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package htw.berlin.wi.prog2;

import htw.berlin.wi.prog2.service.parsing.DummyInputParser;
import htw.berlin.wi.prog2.service.parsing.ExtendableInputParser;
import htw.berlin.wi.prog2.service.SandwichBuilder;
import htw.berlin.wi.prog2.ui.CommandLineUI;
import htw.berlin.wi.prog2.ui.UserInputWrapper;

public class SandwichBotApp {
    public static void main(String[] args) {
        ExtendableInputParser parser = new DummyInputParser();
        SandwichBuilder builder = new SandwichBuilder(SandwichBuilder.CreationStyle.PRECOMPUTED);
        CommandLineUI clui = new CommandLineUI(new UserInputWrapper(System.in, System.out), builder, parser);
        clui.launch();
    }
}
